RUN_NAME: 'RecGNN'
ALGORITHM: 'dijkstra'
MODEL:
  DECODER_USE_LAST_HIDDEN: True
  PROCESSOR_USE_LAST_HIDDEN: True
  PROCESSOR:
    NAME: "RecGNNConv"
    KWARGS: [{"layers":2, "use_bn": True, "is_weighted": True,  "aggr": "max"}]
    LAYERNORM:
      ENABLE: True
      MODE: "node"
  GRU:
    ENABLE: False

TRAIN:
  LOSS:
    OUTPUT_LOSS_WEIGHT: 1.0
    HINT_LOSS_WEIGHT: 0.0
    HIDDEN_LOSS_WEIGHT: 0.01
  MAX_EPOCHS: 100
  BATCH_SIZE: 8

  ENABLE: True
  NUM_WORKERS: 2
  EARLY_STOPPING_PATIENCE: 30
  OPTIMIZER:
    LR: 0.0008

  SCHEDULER:
    ENABLE: True
    NAME: "ReduceLROnPlateau"
    PARAMS: [{"mode": "min", "factor": 0.1, "patience": 10, "verbose": True}]

TEST:
  BATCH_SIZE: 4

LOGGING:
  WANDB:
    GROUP: 'dijkstra'
